name: "Announce New Release - Discord"
on:
  release:
    types:
      - "published"
jobs:
  announce-new-release-discord:
    name: "Announce New Release - Discord (Reusable Workflow)"
    uses: "hugoalh/hugoalh/.github/workflows/announce-new-release-discord.yml@main"
    with:
      name: "GitHub Actions Toolkit (PowerShell)"
      color: "#0072C6"
      thumbnail: "https://i.imgur.com/OhKCMwk.png"
      releases: |
        **- GitHub (& Changelog):** ${{github.event.release.html_url}}
        **- PowerShell Gallery:** https://www.powershellgallery.com/packages/hugoalh.GitHubActionsToolkit
    secrets:
      DISCORD_WEBHOOK: "${{secrets.DISCORD_HXHS_PROJECTNEWRELEASEANNOUNCER_WEBHOOK}}"
