name: "Announce New Release - Discord"
on:
  release:
    types:
      - "published"
jobs:
  announce-new-release-discord:
    name: "Announce New Release - Discord"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/send-discord-webhook-ghaction@v4.2.2"
        with:
          key: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_PROJECTNEWRELEASEANNOUNCER}}"
          payload: |
            content: |
              **__GitHub Actions Toolkit (PowerShell)__**

              Version ${{github.event.release.name}} (${{github.event.release.tag_name}}) is released and available on:

              - **GitHub Repository Release (& Changelog):** <${{github.event.release.html_url}}>
              - **PowerShell Gallery:** <https://www.powershellgallery.com/packages/hugoalh.GitHubActionsToolkit>
            embeds:
              - description: |
                  **__GitHub Actions Toolkit (PowerShell)__**

                  ${{github.event.repository.description}}

                  - **GitHub:** ${{github.event.repository.html_url}}
                color: "44,85,145"
                thumbnail:
                  url: "https://i.imgur.com/PRyLxK8.png"
          wait: "true"
