# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "PowerShell - Publish - Gallery - Module"
on:
  release:
    types:
      - "published"
  workflow_dispatch:
permissions:
  contents: "write"
jobs:
  main:
    name: "Main"
    uses: "hugoalh/hugoalh/.github/workflows/call-powershell-publish-gallery-module-0.yml@main"
    with:
      builder: "_build-package.ps1"
      path: ".\\hugoalh.GitHubActionsToolkit\\"
    secrets:
      POWERSHELLGALLERY_TOKEN: "${{secrets.POWERSHELLGALLERY_TOKEN}}"
