# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Publish PowerShell Module"
on:
  release:
    types:
      - "published"
  workflow_dispatch:
jobs:
  main:
    name: "Main"
    permissions:
      contents: "write"
    uses: "hugoalh/hugoalh/.github/workflows/call-publish-powershell-module-0.yml@main"
    with:
      builder: "_build-package.ps1"
      context: ".\\hugoalh.GitHubActionsToolkit\\"
    secrets:
      POWERSHELLGALLERY_TOKEN: "${{secrets.POWERSHELLGALLERY_TOKEN}}"
