name: "Publish - PowerShell Gallery - Module"
on:
  release:
    types:
      - "published"
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
jobs:
  publish-psg-module:
    name: "Publish - PowerShell Gallery - Module"
    runs-on: "windows-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.2.0"
      - name: "Modify PowerShell Repository"
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy 'Trusted' -Verbose
      - name: "Setup PowerShellGet"
        run: |
          Install-Module -Name 'PowerShellGet' -MinimumVersion '2.2.5' -Scope 'AllUsers' -AcceptLicense -Confirm:$False -Verbose
      - name: "Update PowerShell Modules"
        run: |
          Update-Module -Scope 'AllUsers' -AcceptLicense -Confirm:$False -Verbose
      - name: "Test Publish"
        run: |
          Publish-Module -Path '.\hugoalh.GitHubActionsToolkit\' -NugetAPIKey 'GUID' -WhatIf -Verbose
      - name: "Publish"
        run: |
          Publish-Module -Path '.\hugoalh.GitHubActionsToolkit\' -NugetAPIKey '${{secrets.POWERSHELLGALLERY_TOKEN}}' -Verbose
