# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Publish PowerShell Module - PowerShell Gallery"
on:
  release:
    types:
      - "published"
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
permissions:
  actions: "write"
  checks: "write"
  contents: "write"
  deployments: "write"
  id-token: "write"
  security-events: "write"
  statuses: "write"
jobs:
  main:
    name: "Main"
    uses: "hugoalh/hugoalh/.github/workflows/reusable-publish-powershell-module-psg.yml@main"
    with:
      path: ".\\hugoalh.GitHubActionsToolkit\\"
    secrets:
      POWERSHELLGALLERY_TOKEN: "${{secrets.POWERSHELLGALLERY_TOKEN}}"
