name: "Publish PowerShell Module - PowerShell Gallery"
on:
  release:
    types:
      - "published"
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
jobs:
  publish-powershell-module-psg:
    name: "Publish PowerShell Module - PowerShell Gallery"
    runs-on: "windows-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.4.0"
      - name: "Setup PowerShell Environment"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v1.1.0"
        with:
          toolkit_setup: "false"
      - name: "Test Publish"
        run: |
          Publish-Module -Path '.\hugoalh.GitHubActionsToolkit\' -NugetAPIKey 'GUID' -WhatIf -Verbose
      - name: "Publish"
        run: |
          Publish-Module -Path '.\hugoalh.GitHubActionsToolkit\' -NugetAPIKey '${{secrets.POWERSHELLGALLERY_TOKEN}}' -Verbose
