name: "Publish PowerShell Module - PowerShell Gallery"
on:
  release:
    types:
      - "published"
  workflow_dispatch:
defaults:
  run:
    shell: "pwsh"
jobs:
  main:
    name: "Main"
    uses: "hugoalh/hugoalh/.github/workflows/publish-powershell-module-psg.yml@main"
    with:
      path: ".\\hugoalh.GitHubActionsToolkit\\"
    secrets:
      POWERSHELLGALLERY_TOKEN: "${{secrets.POWERSHELLGALLERY_TOKEN}}"
