name: "Scan Virus"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
  workflow_dispatch:
    inputs:
      git_deep:
        description: "{boolean} Scan deeper for Git repository."
        required: false
        default: "true"
jobs:
  parse-inputs:
    name: "(Parse Inputs)"
    runs-on: "ubuntu-latest"
    steps:
      - run: |
          [string]$GitDeep = '${{github.event.inputs.git_deep}}'
          if ($GitDeep.Length -eq 0) {
            $GitDeep = 'false'
          }
          Write-Host -Object "::set-output name=git_deep::$GitDeep"
        id: "parser"
        shell: "pwsh"
    outputs:
      git_deep: "${{steps.parser.outputs.git_deep}}"
  scan-virus:
    name: "Scan Virus"
    runs-on: "ubuntu-latest"
    needs:
      - "parse-inputs"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.2"
        with:
          fetch-depth: 0
      - name: "Scan Repository"
        uses: "hugoalh/scan-virus-ghaction@v0.6.1"
        with:
          git_deep: "${{needs.parse-inputs.outputs.git_deep}}"
          yara_enable: "true"
